networks:
  vga-network:
    driver: bridge

services:
  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: vga_owasp_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "3007"
      POSTGRES_DB: vga_store
    ports:
      - "5434:5432"
    networks:
      - vga-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d vga_store"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend/vgashop
      dockerfile: Dockerfile
    container_name: vga_owasp_backend
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/vga_store?useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=3007
    networks:
      - vga-network
    volumes:
      - vga_uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  admin-frontend:
    build:
      context: ./fontend/admin
      dockerfile: Dockerfile
    container_name: vga_owasp_admin
    ports:
      - "5176:80"
    networks:
      - vga-network
    depends_on:
      - backend

  user-frontend:
    build:
      context: ./fontend/user
      dockerfile: Dockerfile
    container_name: vga_owasp_user
    ports:
      - "5175:80"
    networks:
      - vga-network
    depends_on:
      - backend

volumes:
  pgdata:
  vga_uploads: